<a href="https://colab.research.google.com/github/kanishka2004-ai/Deep_Learning_Assignment/blob/main/lost_cost__function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [ ]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

In [ ]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [ ]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [ ]:
mae_np(y_predicted, y_true)

np.float64(0.5)

In [ ]:
np.log([0])

<ipython-input-11-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
epsilon = 1e-15

In [ ]:
np.log([1e-15])

array([-34.53877639])

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [ ]:
1-epsilon

0.999999999999999

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)

In [ ]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [ ]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

In [ ]:
#Without Numpy
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    mse_value = total_error / len(y_predicted)
    return mse_value

print(mse(y_predicted, y_true))

0.366


In [ ]:
#With Numpy
def mse_np(y_predicted, y_true):
    return np.mean((y_predicted - y_true) ** 2)

print(mse_np(y_predicted, y_true))

0.366
